### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/grimsi/gameyfin/GameyfinApplication has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 62.0

### ISSUE THREAD

**Issue by GulyFMG** [grimsi/gameyfin#192]
**Describe the bug**
Tried the new ARM image but i can spin it up always get the exit code 1.

**To Reproduce**
1. use the new image from https://hub.docker.com/r/grimsi/gameyfin/tags
2. Docker compose up

![imagem](https://github.com/grimsi/gameyfin/assets/41542940/d450005b-6c3e-42eb-9d00-47acee25ed4c)

**Expected behavior**
Should run a new instance

**General info (please complete the following information):**
 - Installation method: docker
 - Java version (if installation method is "bare metal"): [e.g. Java 18]
 - Browser (if bug is in the Web UI) [e.g. chrome, safari]
 - Gameyfin version [e.g. v1.4.2]

**Additional context**
`gameyfin  | Exception in thread "main" java.lang.UnsupportedClassVersionError: de/grimsi/gameyfin/GameyfinApplication has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 62.0
gameyfin  |     at java.base/java.lang.ClassLoader.defineClass1(Native Method)
gameyfin  |     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
gameyfin  |     at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
gameyfin  |     at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
gameyfin  |     at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
gameyfin  |     at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
gameyfin  |     at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
gameyfin  |     at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
gameyfin  |     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
gameyfin  |     at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
gameyfin  |     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
gameyfin  |     at java.base/java.lang.Class.forName0(Native Method)
gameyfin  |     at java.base/java.lang.Class.forName(Class.java:488)
gameyfin  |     at java.base/java.lang.Class.forName(Class.java:467)
gameyfin  |     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
gameyfin  |     at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
gameyfin  |     at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
gameyfin  |     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
gameyfin exited with code 1`

**Comment by GulyFMG** [comment]
Just tested the new build and works as intended.

![imagem](https://github.com/grimsi/gameyfin/assets/41542940/1b9260d9-7876-483f-8a62-faba843c5866)

Thank you for the fast fix.
