### ISSUE TITLE
A file path that is implicitly relative to the current working directory is not allowed in the database URL

### ISSUE THREAD

**Issue by orcutt989** [grimsi/gameyfin#28]
Seems as if deafult settings might not work or instructions could use a little more specificity.

I tried adding a specific dir for DB and cache but I get same error.

```
# Uncomment if you want to change the port from 8080
server.port=80

# Gameyfin admin interface username and password
gameyfin.user=<your username here>
gameyfin.password=<your password here>

# Gameyfin source folders
gameyfin.sources=F:\Gameyfin Games

# Uncomment if you want to specify the Gameyfin database path (default is <game library root>/.gameyfin/db)
# gameyfin.db=<custom path to db file>

# Uncomment if you want to specify the Gameyfin cache path (default is <game library root>/.gameyfin/cache)
# gameyfin.cache=<custom path to cache folder>

# Your twitch client-id and client-secret
gameyfin.igdb.api.client-id=redacted
gameyfin.igdb.api.client-secret=redacted
```

```
PS C:\gameyfin> java --version
openjdk 20-ea 2023-03-21
OpenJDK Runtime Environment SapMachine (build 20-ea+17)
OpenJDK 64-Bit Server VM SapMachine (build 20-ea+17, mixed mode, sharing)
PS C:\gameyfin> java -jar gameyfin.jar

  _____                            ___   _
 / ___/ ___ _  __ _  ___   __ __  / _/  (_)  ___
/ (_ / / _ `/ /  ' \/ -_) / // / / _/  / /  / _ \
\___/  \_,_/ /_/_/_/\__/  \_, / /_/   /_/  /_//_/
                         /___/

Gameyfin 1.2.1
Powered by Spring Boot 2.7.1


2022-10-06 21:39:41.026  INFO 14480 --- [           main] de.grimsi.gameyfin.GameyfinApplication   : Starting GameyfinApplication v1.2.1 using Java 20-ea on DESKTOP-186TQSV with PID 14480 (C:\gameyfin\gameyfin.jar started by jimmy in C:\gameyfin)
2022-10-06 21:39:41.027  INFO 14480 --- [           main] de.grimsi.gameyfin.GameyfinApplication   : No active profile set, falling back to 1 default profile: "default"
2022-10-06 21:39:42.089  INFO 14480 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-10-06 21:39:42.307  INFO 14480 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 210 ms. Found 7 JPA repository interfaces.
2022-10-06 21:39:43.245  INFO 14480 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2022-10-06 21:39:43.260  INFO 14480 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-10-06 21:39:43.260  INFO 14480 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.64]
2022-10-06 21:39:43.339  INFO 14480 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2252 ms
2022-10-06 21:39:43.573  INFO 14480 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 8.5.13 by Redgate
2022-10-06 21:39:43.573  INFO 14480 --- [           main] o.f.c.internal.license.VersionPrinter    : See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
2022-10-06 21:39:43.573  INFO 14480 --- [           main] o.f.c.internal.license.VersionPrinter    :
2022-10-06 21:39:43.589  INFO 14480 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-10-06 21:39:44.654 ERROR 14480 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

org.h2.jdbc.JdbcSQLNonTransientConnectionException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:F:Gameyfin Gamesdb/gameyfin_db". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:678) ~[h2-2.1.214.jar!/:na]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.214.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:223) ~[h2-2.1.214.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:199) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:464) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.Engine.openSession(Engine.java:49) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.Engine.openSession(Engine.java:222) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.Engine.createSession(Engine.java:201) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338) ~[h2-2.1.214.jar!/:na]
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122) ~[h2-2.1.214.jar!/:na]
        at org.h2.Driver.connect(Driver.java:59) ~[h2-2.1.214.jar!/:na]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar!/:na]
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48) ~[flyway-core-8.5.13.jar!/:na]
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75) ~[flyway-core-8.5.13.jar!/:na]
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:147) ~[flyway-core-8.5.13.jar!/:na]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[flyway-core-8.5.13.jar!/:na]
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.7.1.jar!/:2.7.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at de.grimsi.gameyfin.GameyfinApplication.main(GameyfinApplication.java:13) ~[classes!/:1.2.1]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[gameyfin.jar:1.2.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[gameyfin.jar:1.2.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[gameyfin.jar:1.2.1]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[gameyfin.jar:1.2.1]

2022-10-06 21:39:44.654  WARN 14480 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:F:Gameyfin Gamesdb/gameyfin_db". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-214]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 90011
Error Code : 90011
Message    : A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:F:Gameyfin Gamesdb/gameyfin_db". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-214]

2022-10-06 21:39:44.667  INFO 14480 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-10-06 21:39:44.668  INFO 14480 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-10-06 21:39:44.714 ERROR 14480 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:F:Gameyfin Gamesdb/gameyfin_db". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-214]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 90011
Error Code : 90011
Message    : A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:F:Gameyfin Gamesdb/gameyfin_db". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-214]

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at de.grimsi.gameyfin.GameyfinApplication.main(GameyfinApplication.java:13) ~[classes!/:1.2.1]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[gameyfin.jar:1.2.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[gameyfin.jar:1.2.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[gameyfin.jar:1.2.1]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[gameyfin.jar:1.2.1]
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:F:Gameyfin Gamesdb/gameyfin_db". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-214]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 90011
Error Code : 90011
Message    : A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:F:Gameyfin Gamesdb/gameyfin_db". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-214]

        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60) ~[flyway-core-8.5.13.jar!/:na]
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75) ~[flyway-core-8.5.13.jar!/:na]
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:147) ~[flyway-core-8.5.13.jar!/:na]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[flyway-core-8.5.13.jar!/:na]
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.7.1.jar!/:2.7.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.21.jar!/:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.21.jar!/:5.3.21]
        ... 22 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:F:Gameyfin Gamesdb/gameyfin_db". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:678) ~[h2-2.1.214.jar!/:na]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.214.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:223) ~[h2-2.1.214.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:199) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:464) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.Engine.openSession(Engine.java:49) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.Engine.openSession(Engine.java:222) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.Engine.createSession(Engine.java:201) ~[h2-2.1.214.jar!/:na]
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338) ~[h2-2.1.214.jar!/:na]
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122) ~[h2-2.1.214.jar!/:na]
        at org.h2.Driver.connect(Driver.java:59) ~[h2-2.1.214.jar!/:na]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar!/:na]
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48) ~[flyway-core-8.5.13.jar!/:na]
        ... 28 common frames omitted
```

**Comment by orcutt989** [comment]
I was able to move past this error with -
```
# Gameyfin source folders
gameyfin.sources=.
```

And moving gameyfin.jar to the game dir.

**Comment by grimsi** [comment]
It just took a closer look at your config and I think that you missed escaping the backslash.
Try it with this configuration:
`gameyfin.sources=F:\\Gameyfin Games`

**Comment by orcutt989** [comment]
Sounds good. Maybe we could put something about that in the README or handle it the app?

**Comment by grimsi** [comment]
Glad you found a way to get it working :)
As for your proposal: I have already planned to improve the documentation since the popularity of Gameyfin increased a week ago. Also there are currently plans to move the whole library management to the Web UI Admin screens (so libraries can be added and removed in the frontend instead of via the environment variables), just as you may know it from Plex or Jellyfin. Although I can't promise a timeline on that.
