### ISSUE TITLE
1.2.2 Wont Start - HideInternalFolderOnDOS issue

### ISSUE THREAD

**Issue by jshackles** [grimsi/gameyfin#52]
Gameyfin updated to 1.2.2, and now fails to start with the following error

`2022-10-14 16:35:32.645  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-10-14 16:35:32.669  INFO 1 --- [           main] de.grimsi.gameyfin.GameyfinApplication   : Started GameyfinApplication in 14.272 seconds (JVM running for 15.171)
2022-10-14 16:35:32.740 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
HandlerMethod details: 
Bean [de.grimsi.gameyfin.config.FilesystemConfig$$EnhancerBySpringCGLIB$$c78278ee]
Method [public void de.grimsi.gameyfin.config.FilesystemConfig.hideInternalFolderOnDOS() throws java.io.IOException]
Resolved arguments: 
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:361) ~[spring-context-5.3.21.jar!/:5.3.21]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.21.jar!/:5.3.21]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.21.jar!/:5.3.21]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.21.jar!/:5.3.21]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.21.jar!/:5.3.21]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.21.jar!/:5.3.21]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.21.jar!/:5.3.21]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.21.jar!/:5.3.21]
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114) ~[spring-boot-2.7.1.jar!/:2.7.1]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.1.jar!/:2.7.1]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.7.1.jar!/:2.7.1]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.7.1.jar!/:2.7.1]
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.1.jar!/:2.7.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-2.7.1.jar!/:2.7.1]
	at de.grimsi.gameyfin.GameyfinApplication.main(GameyfinApplication.java:13) ~[classes!/:1.2.2]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[gameyfin.jar:1.2.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[gameyfin.jar:1.2.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[gameyfin.jar:1.2.2]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[gameyfin.jar:1.2.2]
Caused by: java.nio.file.FileSystemException: /opt/gameyfin-library/.gameyfin: Operation not supported
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
	at java.base/sun.nio.fs.LinuxDosFileAttributeView.updateDosAttribute(LinuxDosFileAttributeView.java:278) ~[na:na]
	at java.base/sun.nio.fs.LinuxDosFileAttributeView.setHidden(LinuxDosFileAttributeView.java:196) ~[na:na]
	at java.base/sun.nio.fs.LinuxDosFileAttributeView.setAttribute(LinuxDosFileAttributeView.java:91) ~[na:na]
	at java.base/sun.nio.fs.AbstractFileSystemProvider.setAttribute(AbstractFileSystemProvider.java:81) ~[na:na]
	at java.base/java.nio.file.Files.setAttribute(Files.java:1919) ~[na:na]
	at de.grimsi.gameyfin.config.FilesystemConfig.hideInternalFolderOnDOS(FilesystemConfig.java:55) ~[classes!/:1.2.2]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.21.jar!/:5.3.21]
	... 21 common frames omitted
2022-10-14 16:35:34.795  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-10-14 16:35:34.797  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-10-14 16:35:34.818  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.`

I tried manually marking my .gameyfin folder as hidden and restarting the application, but got the same result.  My library folder is on a Synology NAS, if that helps.

**Comment by grimsi** [comment]
Sorry for that, I already think I know why this happens. I set the attribute "dos:hidden" to true, but on UNIX systems this isn't possible since they don't have a DOS file system (obviously). On UNIX it's already hidden due to the dot..
I will add a check for the OS.

Also this is another reason for #33 😉

**Comment by grimsi** [comment]
Can you check if this version fixes your issue?
Docker: https://hub.docker.com/layers/grimsi/gameyfin/1.2.3-SNAPSHOT/images/sha256-9d14d5cf15a281ccfea0022bb7574c8d3f43877d434f6ca17a1fc217c4fe6a98?context=repo

JAR file: https://github.com/grimsi/gameyfin/actions/runs/3253690812

**Comment by jshackles** [comment]
That version works great, Gameyfin no longer crashes on startup

**Comment by grimsi** [comment]
Great, thanks for your feedback. I released 1.2.3 which includes this bugfix and a few other small improvements.

https://github.com/grimsi/gameyfin/releases/tag/v1.2.3
